name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Install shellcheck
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          sudo apt-get update && sudo apt-get install -y shellcheck
        else
          brew install shellcheck
        fi
        
    - name: Lint scripts
      run: |
        shellcheck install.sh
        shellcheck src/zs
        shellcheck test.sh
        
    - name: Run tests
      run: ./test.sh
      
    - name: Test installation
      run: |
        ./install.sh --local --prefix /tmp/test-install
        /tmp/test-install/bin/zs help